# Generated by Django 3.0.4 on 2020-03-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200309_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=11, verbose_name='手机号')),
                ('code', models.CharField(max_length=6, verbose_name='验证码')),
                ('type', models.CharField(max_length=6, verbose_name='验证码类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
            ],
            options={
                'verbose_name': '验证码',
                'verbose_name_plural': '验证码',
                'unique_together': {('telephone', 'code')},
            },
        ),
    ]
