# Generated by Django 3.0.4 on 2020-03-12 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='分类名')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='flower.Category', verbose_name='父级分类')),
            ],
            options={
                'verbose_name': '分类表',
                'verbose_name_plural': '分类表',
            },
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名字')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='描述')),
                ('price', models.PositiveIntegerField(verbose_name='价格')),
                ('price_ori', models.PositiveIntegerField(verbose_name='原价')),
                ('sales', models.PositiveIntegerField(default=0, verbose_name='销量')),
                ('flower_language', models.CharField(blank=True, max_length=200, null=True, verbose_name='花语')),
                ('material', models.CharField(blank=True, max_length=200, null=True, verbose_name='材质')),
                ('distribution', models.CharField(default='全国', max_length=200)),
                ('mainImg', models.ImageField(upload_to='flowerimg', verbose_name='主图')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flower.Category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '鲜花表',
                'verbose_name_plural': '鲜花表',
            },
        ),
        migrations.CreateModel(
            name='FlowerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='flowerdetailimg/', verbose_name='鲜花图文')),
                ('type', models.CharField(choices=[('banner', '轮播图'), ('info', '图文简介')], max_length=6, verbose_name='类型')),
                ('index', models.IntegerField(verbose_name='顺序索引')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flower.Flower', verbose_name='鲜花')),
            ],
            options={
                'verbose_name': '鲜花图片',
                'verbose_name_plural': '鲜花图片',
            },
        ),
    ]
