# Generated by Django 3.0.4 on 2020-03-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='sales',
            field=models.PositiveIntegerField(default=0, verbose_name='销量'),
        ),
    ]
