# Generated by Django 3.0.4 on 2020-03-09 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flower', '0002_auto_20200309_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reveiver', models.CharField(max_length=20, verbose_name='收货人')),
                ('serviceTime', models.DateTimeField(verbose_name='送达时间')),
                ('leaveMessage', models.CharField(max_length=200, verbose_name='留言')),
                ('remark', models.CharField(max_length=200, verbose_name='备注')),
                ('state', models.CharField(choices=[('undo', '未支付'), ('finish', '已支付')], max_length=6, verbose_name='状态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单表',
                'verbose_name_plural': '订单表',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField(default=0, verbose_name='数量')),
                ('price', models.PositiveIntegerField(verbose_name='价格')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flower.Flower', verbose_name='鲜花')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.Order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单详情表',
                'verbose_name_plural': '订单详情表',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField(default=0, verbose_name='数量')),
                ('price', models.PositiveIntegerField(verbose_name='价格')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flower.Flower', verbose_name='鲜花')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
            },
        ),
    ]
