# Generated by Django 3.0.4 on 2020-03-12 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flower', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField(default=0, verbose_name='数量')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='订单号')),
                ('trader_sn', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='交易号')),
                ('state', models.CharField(choices=[('undo', '未支付'), ('finish', '已支付'), ('cancle', '已取消')], default='undo', max_length=6, verbose_name='订单状态')),
                ('leaveMessage', models.CharField(blank=True, max_length=200, null=True, verbose_name='留言')),
                ('money', models.IntegerField(verbose_name='订单金额')),
                ('reveiver', models.CharField(max_length=20, verbose_name='收货人')),
                ('reveiveAddress', models.CharField(max_length=50, verbose_name='收货地址')),
                ('reveivePhone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('serviceTime', models.DateTimeField(verbose_name='送达时间')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '订单表',
                'verbose_name_plural': '订单表',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField(verbose_name='数量')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flower.Flower', verbose_name='鲜花')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.Order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单详情表',
                'verbose_name_plural': '订单详情表',
            },
        ),
    ]
