# Generated by Django 3.0.4 on 2020-03-09 10:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0002_auto_20200309_1731'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='leaveMessage',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='留言'),
        ),
        migrations.AlterField(
            model_name='order',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='备注'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'flower')},
        ),
        migrations.AlterUniqueTogether(
            name='orderdetail',
            unique_together={('order', 'flower')},
        ),
    ]
