# Generated by Django 3.0.4 on 2020-03-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20200309_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='money',
            field=models.IntegerField(default=90, verbose_name='订单金额'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_sn',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='订单号'),
        ),
        migrations.AddField(
            model_name='order',
            name='reveiveAddress',
            field=models.CharField(default='郑州', max_length=50, verbose_name='收货地址'),
        ),
        migrations.AddField(
            model_name='order',
            name='reveivePhone',
            field=models.CharField(default='15138001200', max_length=11, verbose_name='联系电话'),
        ),
        migrations.AddField(
            model_name='order',
            name='trader_sn',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='交易号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='reveiver',
            field=models.CharField(default='张飞', max_length=20, verbose_name='收货人'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('undo', '未支付'), ('finish', '已支付'), ('cancle', '已取消')], default='undo', max_length=6, verbose_name='订单状态'),
        ),
    ]
