# Generated by Django 3.0.4 on 2020-03-12 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20200312_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='price',
        ),
    ]
