# Generated by Django 3.0.3 on 2020-02-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='zzy', max_length=20),
        ),
    ]
