# Generated by Django 3.0.3 on 2020-02-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0004_auto_20200215_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.CharField(blank=True, db_column='description', help_text='请输入书籍备注嘻嘻', max_length=50, null=True),
        ),
    ]
