# Generated by Django 3.0.3 on 2020-02-15 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0007_auto_20200215_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=11, verbose_name='手机号')),
                ('email', models.EmailField(default='496575233@qq.com', max_length=254)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booktest.Account')),
            ],
        ),
        migrations.AlterField(
            model_name='hero',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heros', to='booktest.Book'),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
