# Generated by Django 3.0.3 on 2020-02-17 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0009_auto_20200215_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concact',
            name='account',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='articles',
        ),
        migrations.AlterField(
            model_name='hero',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktest.Book'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Concact',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
