# Generated by Django 3.0.4 on 2020-03-09 09:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flower', '0002_auto_20200309_1731'),
        ('user_operate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collect',
            options={'verbose_name': '收藏表', 'verbose_name_plural': '收藏表'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '评论表', 'verbose_name_plural': '评论表'},
        ),
        migrations.AlterModelOptions(
            name='commentimg',
            options={'verbose_name': '评论图表', 'verbose_name_plural': '评论图表'},
        ),
        migrations.AlterUniqueTogether(
            name='collect',
            unique_together={('user', 'flower')},
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('user', 'flower')},
        ),
    ]
